### ISSUE TITLE
可能是材质导致的闪退

### ISSUE THREAD

**Issue by wtksana** [GeForceLegend/Minecraft-Default-3D#10]
游戏版本 1.12.2
材质版本 3D.Default.1.12_Optifine.v1.3.2
optifine版本 hd_u_f5
打开有jei的页面（比如打开背包）就卡死 报错
jei版本 jei_1.12.2-4.16.1.301

换了几个jei版本 和abyssalcraft的版本 都报错

去掉材质后没问题
初步判断可能是材质引起的

闪退报告：

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin ([前置]Forgelin-1.8.4.jar)
  AppleCore ([苹果核]AppleCore-mc1.12.2-3.1.4.jar)
  Botania Tweaks Core ([植魔附属]botaniatweaks-1.8.6.jar)
  JechCore ([JEI附属]JustEnoughCharacters-1.12.0-3.3.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  LoadingPlugin ([随意作品]RandomThings-MC1.12.2-4.2.5.jar)
  CTMCorePlugin ([凿子前置]CTM-MC1.12.2-1.0.1.30.jar)
  PhosphorFMLLoadingPlugin ([优化]phosphor-1.12.2-0.2.6+build50-universal.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  AALoadingPlugin ([奥术档案馆]arcanearchives-0.2.0.13.jar)
  LoadingPlugin ([自定义主界面前置]ResourceLoader-MC1.12.1-1.5.3.jar)
  PassableLeavesCore (PassableLeavesCore-1.12.2-1.0.0.jar)
  OpenModsCorePlugin ([开放式方块前置]OpenModsLib-1.12.2-0.12.1.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  MekanismCoremod ([通用机械]Mekanism-1.12.2-9.8.3.390.jar)
  AstralCore ([星辉魔法]astralsorcery-1.12.2-1.10.20 .jar)
  Inventory Tweaks Coremod ([r键整理]InventoryTweaks-1.63.jar)
  NWRTweak ([爬墙红石]redstonepaste-mc1.12-1.7.5.jar)
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  CoreMod ([前置]Aroma1997Core-1.12.2-2.0.0.0.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  Quark Plugin ([夸克]Quark-r1.6-177.jar)
  MalisisCorePlugin ([更多的门前置]malisiscore-1.12.2-6.5.1.jar)
  RandomPatches ([优化]randompatches-1.12.2-1.15.0.2.jar)
  SurgeLoadingPlugin ([优化]Surge-1.12.2-2.0.77.jar)
  CorePlugin ([平滑字体]SmoothFont-mc1.12.2-2.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 11/8/20 7:56 PM
Description: Rendering ingredient

java.lang.NullPointerException: Rendering ingredient
	at com.shinoow.abyssalcraft.client.ClientProxy.lambda$init$60(ClientProxy.java:183)
	at com.shinoow.abyssalcraft.client.ClientProxy$$Lambda$4753/000000000000000000.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:357)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:171)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3855_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.shinoow.abyssalcraft.client.ClientProxy.lambda$init$60(ClientProxy.java:183)
	at com.shinoow.abyssalcraft.client.ClientProxy$$Lambda$4753/000000000000000000.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:357)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:171)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:136)

-- Ingredient being rendered --
Details:
	Mod Name: AbyssalCraft
	Registry Name: abyssalcraft:scroll
	Display Name: 基础卷轴
	String Name: 1xitem.scroll@0
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:271)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:34)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3855_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- JEI render details --
Details:
	Unique Id (for Blacklist): abyssalcraft:scroll:0
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1xitem.scroll@0 abyssalcraft:scroll nbt:{}
	Filter Text: jichuj
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (480, 269). Absolute: (960, 540)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2
...

**Comment by GeForceLegend** [comment]
能否在闪退发生后发一下log文件，我个人更习惯看log

**Comment by GeForceLegend** [comment]
Close because no enough information
